const { Pool } = require('pg');

const databaseUrl = process.env.DATABASE_URL || 'postgresql://postgres@localhost:5432/azmera_db';

const pool = new Pool({
    connectionString: databaseUrl,
});

(async () => {
    try {
        console.log('Connecting to database...');

        // 0. List tables
        const tablesRes = await pool.query("SELECT table_name FROM information_schema.tables WHERE table_schema = 'public'");
        console.log('Tables in DB:', tablesRes.rows.map(r => r.table_name).join(', '));

        // Determine User table name
        const userTableInfo = tablesRes.rows.find(r => r.table_name.toLowerCase() === 'user' || r.table_name.toLowerCase() === 'users');
        if (!userTableInfo) throw new Error('User table not found');
        const userTableName = '"' + userTableInfo.table_name + '"';
        console.log(`Using User table: ${userTableName}`);

        // Determine IoTDevice table name
        const iotTableInfo = tablesRes.rows.find(r => r.table_name.toLowerCase() === 'iotdevice' || r.table_name.toLowerCase() === 'iot_devices');
        // Note: older logic used iot_devices, new schema uses IoTDevice. 
        // db push might have created IoTDevice.
        if (!iotTableInfo) {
            // If not found, maybe I need to check schema again?
            console.warn('IoTDevice table not found immediately? Checking again...');
        }
        const iotTableName = iotTableInfo ? '"' + iotTableInfo.table_name + '"' : '"IoTDevice"'; // Default to expected
        console.log(`Using IoT table: ${iotTableName}`);

        // 1. Get a user ID
        // Note: Column names might also be case sensitive if generated by Prisma? Usually not for fields unless @map.
        // Prisma `email` -> `email`. `id` -> `id`.
        const userRes = await pool.query(`SELECT id, email FROM ${userTableName} WHERE email = 'abebe@farmer.com' LIMIT 1`);

        let userId;
        if (userRes.rows.length === 0) {
            console.log('User abebe@farmer.com not found. Trying any user...');
            const anyUser = await pool.query(`SELECT id, email FROM ${userTableName} LIMIT 1`);
            if (anyUser.rows.length === 0) {
                throw new Error('No users found in DB. Cannot test IoT device creation.');
            }
            console.log('Using user:', anyUser.rows[0]);
            userId = anyUser.rows[0].id;
        } else {
            console.log('Using user:', userRes.rows[0]);
            userId = userRes.rows[0].id;
        }

        // 2. Insert IoT Device
        console.log(`Inserting into ${iotTableName}...`);
        // Note: Postgres is case sensitive for column names if they key mismatch or were quoted in creation.
        // Prisma usually doesn't quote unless necessary.
        // I will try standard names first.
        const deviceId = 'test-device-' + Date.now();
        const insertQuery = `
      INSERT INTO ${iotTableName} (id, name, type, status, "farmerId", "lastSeen", "createdAt", "updatedAt")
      VALUES ($1, $2, $3, $4, $5, NOW(), NOW(), NOW())
      RETURNING id, name
    `;

        const res = await pool.query(insertQuery, [deviceId, 'Test Device', 'soil_moisture', 'online', userId]);
        console.log('Inserted device:', res.rows[0]);

        // 3. Verify
        const selectRes = await pool.query(`SELECT * FROM ${iotTableName} WHERE id = $1`, [deviceId]);
        console.log('Verified device:', selectRes.rows[0]);

        // 4. Cleanup
        await pool.query(`DELETE FROM ${iotTableName} WHERE id = $1`, [deviceId]);
        console.log('Cleaned up test device.');

    } catch (err) {
        console.error('Verification failed:', err);
        process.exit(1);
    } finally {
        await pool.end();
    }
})();
